language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t btsao604/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true btsao604/docker-react npm run test